### ISSUE TITLE
no possibility to add 2 allowed hosts with different community strings for SNMPv2

### ISSUE THREAD

**Issue by fehoffm** [T-Systems-MMS/puppet-secc_snmpd#11]
a second host will overwrite the first now
should behave in the way, that a second host with second community is written into a new line

example:
rocommunity community1 192.168.0.1
rocommunity community2 192.168.0.2

**Comment by schurzi** [comment]
I did a quick check, this case should be covered in the test cases, and if I try manually this works as well.

I used this manifest:
```
class { 'secc_snmpd':
  service                   => 'test',
  syslocation               => 'at home',
  syscontact                => 'root@me.you',
  v2_enabled                => true,
  v3_enabled                => false,
  v2_community              => 'communitysss',
  v2_host                   => 'localhost',
  enforce_password_security => false,
}

secc_snmpd::config::v2{ "test_127.0.0.2":
  v2_community => 'community',
  v2_host      => '127.0.0.2',
}
```

**Comment by schurzi** [comment]
@fehoffm waiting for a response

**Comment by fehoffm** [comment]
> 
> 
> @fehoffm waiting for a response

thanks a lot, it worked.
