### ISSUE TITLE
$::secc_snmpd::enforce_password_security is not working anymore

### ISSUE THREAD

**Issue by PatrSchu** [T-Systems-MMS/puppet-secc_snmpd#4]
Hier wird ein notify generiert für jede "falsche" community. Der Parameter `::secc_snmpd::enforce_password_security` greift in dieser Version nicht mehr

> Error: Could not retrieve catalog from remote server: Error 500 on SERVER: Server Error: Evaluation Error: Error while evaluating a Resource Statement, Evaluation Error: Error while evaluating a Resource Statement, Duplicate declaration: Notify[Community must contain [a-z],[A-Z],[0-9] characters and special characters!] is already declared in file

**Comment by schurzi** [comment]
hmm ... can you provide steps to reproduce the problem?
Are you defining multiple v2 communities? (that seems to be the problem)

**Comment by schurzi** [comment]
ping @PatrSchu

**Comment by PatrSchu** [comment]
Sry for the late response!
Yes, it`s true. V2 is activated und V3 is deactivated.
Is there something that I have pay attention or some specials when I change to V3?
Thanks in advance!

**Comment by schurzi** [comment]
Using V3 should be straight forward, like documented.
I think I will merge the referenced PR regardless, since it will also solve your Problem with V2. Can you please verify that you are defining multiple V2 communities?

**Comment by schurzi** [comment]
Changes will be in Version 2.0.1, this should appear in approx 30 minutes on Puppetforge
